export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_CLEAR = 'REGISTRATION_CLEAR';
export const GET_ALIAS = 'GET_ALIAS';
export const AUTH = 'AUTH';
export const SET_HOST_NAME = 'SET_HOST_NAME';
export const CLEAR_REG = 'CLEAR_REG';
export const IS_CHANGE_PAGE = 'IS_CHANGE_PAGE';
export const IS_OWN_PAGE = 'IS_OWN_PAGE';
export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION';
export const SEARCH = 'SEARCH';

export const ALERT = 'ALERT';
export const ALERT_SUCCESS = 'ALERT_SUCCESS';
export const ALERT_ERROR = 'ALERT_ERROR';
export const ALERT_OBJECT = 'ALERT_OBJECT';
export const ALERT_CLEAR = 'ALERT_CLEAR';

export const PROFILE = 'PROFILE';
export const USER = 'USER';
export const ACTIVE_USER = 'ACTIVE_USER';

export const SHOW_PLAYER = 'SHOW_PLAYER';
export const HIDE_PLAYER = 'HIDE_PLAYER';

export const POPULATE_SERVICES = 'POPULATE_SERVICES';
// export const GET_SERVICE = 'GET_SERVICE';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';
// export const UPLOAD_SERVICE_IMAGE = 'UPLOAD_SERVICE_IMAGE';
// export const DELETE_SERVICE_IMAGE = 'DELETE_SERVICE_IMAGE';
export const SET_CURRENT_SERVICE = 'SET_CURRENT_SERVICE';
export const RESET_CURRENT_SERVICE = 'RESET_CURRENT_SERVICE';

export const ADD_GROUP_CONTACTS = 'ADD_GROUP_CONTACTS';
export const DELETE_GROUP_CONTACTS = 'DELETE_GROUP_CONTACTS';

export const POPUP_SHOW = 'POPUP_SHOW';
export const POPUP_HIDE = 'POPUP_HIDE';

export const PICK_FEATURES_TAB = 'PICK_FEATURES_TAB';
export const PICK_USERDETAILS_TAB = 'PICK_USERDETAILS_TAB';
export const PICK_ABOUTME_TAB = 'PICK_ABOUTME_TAB';
export const PICK_GLOBAL_MENU_TAB = 'PICK_GLOBAL_MENU_TAB';

export const POPULATE_CONTACTS = 'POPULATE_CONTACTS';
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';

export const POPULATE_NETWORKS = 'POPULATE_NETWORKS';

export const ADDED_PHONE_USER = 'ADDED_PHONE_USER';
export const ADDED_EMAIL_USER = 'ADDED_EMAIL_USER';

export const CHANGE_PHONE_USER = 'CHANGE_PHONE_USER';

export const POPULATE_PORTFOLIO = 'POPULATE_PORTFOLIO';
export const CREATE_PORTFOLIO_WORK = 'ADD_PORTFOLIO_WORK';
export const UPDATE_PORTFOLIO_WORK = 'UPDATE_PORTFOLIO_WORK';
export const DELETE_PORTFOLIO_WORK = 'DELETE_PORTFOLIO_WORK';
export const SET_PORTFOLIO_CURRENT_WORK = 'SET_PORTFOLIO_CURRENT_WORK';
export const RESET_PORTFOLIO_CURRENT_WORK = 'RESET_PORTFOLIO_CURRENT_WORK';

export const POPULATE_CV = 'POPULATE_CV';
export const ADD_CV_ENTITY = 'ADD_CV_ENTITY';
export const UPDATE_CV_ENTITY = 'UPDATE_CV_ENTITY';
export const DELETE_CV_ENTITY = 'DELETE_CV_ENTITY';
export const POPULATE_CV_FORMS = 'POPULATE_CV_FORMS';
export const CREATE_CV_FORM = 'CREATE_CV_FORM';
export const CHANGE_INPUT_CV = 'CHANGE_INPUT_CV';
export const REMOVE_CV_FORM = 'REMOVE_CV_FORM';
export const CLEAR_FROM_FORMS = 'CLEAR_FROM_FORMS';

export const ADDED_REVIEWS = 'ADDED_REVIEWS';
export const ADD_NEW_REVIEW = 'ADD_NEW_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const APPROVE_REVIEW = 'APPROVE_REVIEW';
export const TEST_REVIEW_API = 'TEST_REVIEW_API';
export const GET_ALL_USER_REVIEW_FROM_SERVER =
                 'GET_ALL_USER_REVIEW_FROM_SERVER';
export const REVIEW_ADDED_SUCCESSFULLY_REPORT =
                 'REVIEW_ADDED_SUCCESSFULLY_REPORT';
export const REVIEW_ADDED_REPORT_DELETE = 'REVIEW_ADDED_REPORT_DELETE';

export const ADD_ITEMS_ON_SHOP = 'ADD_ITEMS_ON_SHOP';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';

export const POPULATE_VIDEOS = 'POPULATE_VIDEOS';
export const GET_VIDEO = 'GET_VIDEO';
export const CREATE_VIDEO = 'CREATE_VIDEO';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const DELETE_VIDEO = 'DELETE_VIDEO';
export const UPLOAD_VIDEO_IMAGE = 'UPLOAD_VIDEO_IMAGE';
export const DELETE_VIDEO_IMAGE = 'DELETE_VIDEO_IMAGE';
export const UPLOAD_PROFILE_IMAGE = 'UPLOAD_PROFILE_IMAGE';
export const DELETE_PROFILE_IMAGE = 'DELETE_PROFILE_IMAGE';

export const POPULATE_CATEGORIES = 'POPULATE_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const RESET_CURRENT_CATEGORY = 'RESET_CURRENT_CATEGORY';

export const POPULATE_FRIENDS = 'POPULATE_FRIENDS';
export const POPULATE_FRIENDS_BY_CATEGORY = 'POPULATE_FRIENDS_BY_CATEGORY';
export const ADD_FRIEND = 'ADD_FRIEND';
export const ADD_FRIEND_AND_PAST_TO_SOME_CATEGORY =
                 'ADD_FRIEND_AND_PAST_TO_SOME_CATEGORY';
export const PAST_FRIEND_TO_SOME_CATEGORY = 'PAST_FRIEND_TO_SOME_CATEGORY';
export const REMOVE_FRIEND_FROM_CATEGORY = 'REMOVE_FRIEND_FROM_CATEGORY';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';
export const SET_CURRENT_FRIEND = 'SET_CURRENT_FRIEND';
export const RESET_CURRENT_FRIEND = 'RESET_CURRENT_FRIEND';
export const POPULATE_SCROLL_FRIENDS = 'POPULATE_SCROLL_FRIENDS';

/////////////////  Shop ////////////

export const POPULATE_SHOP = 'POPULATE_SHOP';
export const CREATE_SHOP = 'CREATE_SHOP';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const DELETE_SHOP = 'DELETE_SHOP';
export const SET_CURRENT_SHOP = 'SET_CURRENT_SHOP';
export const RESET_CURRENT_SHOP = 'RESET_CURRENT_SHOP';

//////////////// GOALS TYPE////////////

export const POPULATE_GOALS = 'POPULATE_GOALS';
export const CREATE_GOAL = 'CREATE_GOAL';
export const DELETE_GOAL = 'DELETE_GOAL';
export const UPDATE_GOAL = 'UPDATE_GOAL';
export const LANGUAGE_INIT = 'LANGUAGE_INIT';

////////////////// CUSTOM TAGS //////////

export const POPULATE_CUSTOM_TAGS = 'POPULATE_CUSTOM_TAGS';
export const CREATE_CUSTOM_TAGS = 'CREATE_CUSTOM_TAGS';
export const DELETE_CUSTOM_TAGS = 'DELETE_CUSTOM_TAGS';

